export const GET_INVENTORIES = 'GET_INVENTORIES';
export const ADD_TO_INVENTORIES = 'ADD_TO_INVENTORIES';
export const ADD_CATEGORY_TO_INVENTORIES = 'ADD_CATEGORY_TO_INVENTORIES';
export const REMOVE_FROM_INVENTORIES = 'REMOVE_FROM_INVENTORIES';
export const INIT = 'INIT';
export const NEXT_ID = 'NEXT_ID';